name: Publish `@org-dashed/pkg`

permissions:
  contents: write
  id-token: write

on:
  repository_dispatch:
    types: [publish-pkg]

jobs:
  publish:
    runs-on: "ubuntu-latest"
    steps:
      - name: Publish
        run: echo "${{ github.event.client_payload.releaseId }}"
